name: Mon Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Verification du runner
        run: echo "Le Runner est bien actif sur la machine local"

      - name: Hello World
        run: echo "Hello World depuis le runner self-hosted ✅"
